### ISSUE TITLE
Add Bootstrap to this repository instead of using cdn.jsdelivr.net

### ISSUE THREAD

**Issue by Ta180m** [LadueCS/OpenContest-Web-Lite#1]
@ADawesomeguy Do you know if we could add Bootstrap to this repository (`npm install bootstrap` or something like that) instead of using cdn.jsdelivr.net, or is it just easier overall to use that CDN site?

**Comment by Ta180m** [comment]
We could also download https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css and place it in this repo and use that, but I don't know if that's good practice or not.

**Comment by ADawesomeguy** [comment]
I think for now we can keep the CDN because it's not slow and it's easy but at some point down the line maybe we should migrate.
