### ISSUE TITLE
Figure out root URLs and link

### ISSUE THREAD

**Issue by ADawesomeguy** [LadueCS/OpenContest-Web-Lite#2]
GitHub obviously has their subdirectory for web servers so we have to do something about that.

**Comment by Ta180m** [comment]
Can we use relative links so that we don't have to worry about subdirectories? Maybe there are other hacks as well to get both subdirectories and subdomains to work.

**Comment by ADawesomeguy** [comment]
Could probably grab base URL with Javscript or something.

**Comment by Ta180m** [comment]
I think relative links are probably the cleanest way of doing this. Nice and simple.

**Comment by Ta180m** [comment]
@ADawesomeguy I modified the code to only use relative links. Is that a satisfactory solution?

**Comment by ADawesomeguy** [comment]
Yeah for now at least.
