### ISSUE TITLE
The login page should have a text box for inputting your homeserver

### ISSUE THREAD

**Issue by Ta180m** [LadueCS/OpenContest-Web-Lite#3]
I think the current flow of using the server entered on the home page for use as the homeserver for logging in is kind of confusing. It also creates confusion about the difference between the user's homeserver and the contest server they are browsing. For federated apps, it's especially important to get the UI right so it's not difficult to use.

**Comment by ADawesomeguy** [comment]
I agree, good thinking. We could keep the select on the home screen but also implement one in the login page.

**Comment by Ta180m** [comment]
I feel like the selection on the home page should be more for selecting a contest server to browse.

**Comment by ADawesomeguy** [comment]
Alright, makes sense, I'll modify it tomorrow.
